CREATE TABLE GROUPMATES (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name TEXT NOT NULL,
  age TEXT NOT NULL,
  address TEXT NOT NULL
);

-- insert
INSERT INTO GROUPMATES VALUES (0001, 'Anton', '35', 'Moscow');
INSERT INTO GROUPMATES VALUES (0002, 'Antonina', '24', 'Vladivostok');
INSERT INTO GROUPMATES VALUES (0003, 'Elena', '29', 'Moscow');
INSERT INTO GROUPMATES VALUES (0004, 'Alina', '19', 'Omsk');
INSERT INTO GROUPMATES VALUES (0005, 'Artem', '21', 'Petrozavodsk');
INSERT INTO GROUPMATES VALUES (0006, 'Olga', '18', 'Artem');
INSERT INTO GROUPMATES VALUES (0007, 'Vasiliy', '28', 'Moscow');
INSERT INTO GROUPMATES VALUES (0008, 'Irina', '23', 'Samara');
INSERT INTO GROUPMATES VALUES (0009, 'Marat', '18', 'Moscow');
INSERT INTO GROUPMATES VALUES (0010, 'Agata', '25', 'Ussurisk');
-- fetch 
SELECT * FROM GROUPMATES 
WHERE (address = 'Moscow') AND age >= 18 AND age <= 30;